[book]
authors = ["wangzaixiang"]
language = "en"
src = "src"
title = "learning"

[preprocessor]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output]

[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
